# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6996625553938792034e47be003006fac4c7ccacd2aeba5c8b6fa4155490d8fd61405486ec860fb0dfe4ec762d0568e1f1696f8e9479195820f94cab99615857

test:
  secret_key_base: 109407036bfff00da055e4d09259de67efa31d9cb83eeb0e0577bc6ba32cee4df5264ea2c7b8818fea179ed3fc963f955df40e244dcf7159b0cde4d9a7eccc9e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
